### ISSUE TITLE
Python 3.12 compatibility

### ISSUE THREAD

**Issue by h-pineau** [Resourcecode-project/py-resourcecode#2]
Hi !

Thank you for ResourceCode data and libraries !

Is it planned to update the py-resourcecode to Python 3.12 ?

I would like to use resourcecode together with other packages having 3.12 requirements.

Thank you,

Hélène

**Comment by NRaillard** [comment]
Hi @h-pineau ,
Thanks for you question.
I have updated the workflow and the tests are now passing on python 3.12, so I add it to the list of compatibility.
The new version (I jumped to v1.1.3 since I struggled a little bit to make everything work) is on pypi, make sure to update the package.
Best,
Nicolas.

**Comment by h-pineau** [comment]
Thank you ! The installation is now OK in Python 3.12.
